// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzqhogfjudivwlgjqvxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6cWhvZ2ZqdWRpdndsZ2pxdnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTc3NjQsImV4cCI6MjA1ODc5Mzc2NH0.u06it69QLgl7bTTbJdfIeyr-UjddIeXinkvbLR_zdLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);